### PR TITLE
API V3 to V4

### PR DESCRIPTION
**Pull request by sPooKee**
Switched API Version from v3 to v4

### CODE REVIEW

**Comment by curry684** [comment]
Thanks for the help @sPooKee 

What do you suggest we do with versioning now, should we consider this a new major version?

**Comment by sPooKee** [comment]
Good question ;)
I think a new major version will be okay, I think they won't change much on OAuth in GitLab <= 8.16.
V4 is available since GitLab 8.17.

Since they are working on Scopes, perhaps there are further changes coming...

**Comment by curry684** [comment]
Yeah that's why I'm thinking we may want to leave this hanging until v3 is no longer supported. So I'll merge it into master now for those wanting cutting edge support, and as the v3 removal is scheduled for 9.4 soonest (22nd of July) I'll schedule a reminder for myself at the end of May to look into it again.

**Comment by curry684** [comment]
I upgraded the PHPUnit dependencies as well (was on my list for a while), but the optional link to the Gitlab API Client may also need to be updated (https://github.com/m4tthumphrey/php-gitlab-api/issues/171).

**Comment by curry684** [comment]
https://github.com/omines/oauth2-gitlab/releases/tag/3.0.0
https://packagist.org/packages/omines/oauth2-gitlab

**Pull request merged**
